#!/usr/bin/env bash
set -euo pipefail

usage() {
    cat <<'EOF'
Usage:
  scripts/create-wake-word-workspace.sh "Stacky" [options]

Creates a project-local microWakeWord training workspace with Piper sample
generation, feature generation, training config, model training command, and
ESPHome-style model manifest generation.

Options:
  --id ID                Model id/slug. Default: phrase lowercased with non-alnum as '-'.
  --phoneme TEXT         Piper phoneme input. Use when normal spelling sounds wrong.
  --project-root DIR     Project root for .stacky-wake-words output. Default: current directory.
  --samples N            Piper positive sample count. Default: 1000.
  --batch-size N         Piper batch size. Default: 100.
  --force                Overwrite generated control files if workspace already exists.
  -h, --help             Show this help.

Examples:
  scripts/create-wake-word-workspace.sh "Stacky"
  scripts/create-wake-word-workspace.sh "Hey Frank" --id hey-frank --phoneme "hˈeɪ fɹˈæŋk˺"
EOF
}

slugify() {
    printf '%s' "$1" \
        | tr '[:upper:]' '[:lower:]' \
        | sed -E 's/[^a-z0-9]+/-/g; s/^-+//; s/-+$//'
}

quote_sh() {
    printf "%q" "$1"
}

phrase=""
model_id=""
phoneme=""
project_root="$(pwd)"
samples="1000"
batch_size="100"
force="0"

while [[ $# -gt 0 ]]; do
    case "$1" in
        --id)
            model_id="${2:-}"
            shift 2
            ;;
        --phoneme)
            phoneme="${2:-}"
            shift 2
            ;;
        --project-root)
            project_root="${2:-}"
            shift 2
            ;;
        --samples)
            samples="${2:-}"
            shift 2
            ;;
        --batch-size)
            batch_size="${2:-}"
            shift 2
            ;;
        --force)
            force="1"
            shift
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        -*)
            echo "ERROR: unknown option: $1" >&2
            usage >&2
            exit 1
            ;;
        *)
            if [[ -n "$phrase" ]]; then
                echo "ERROR: phrase already set to '$phrase'" >&2
                exit 1
            fi
            phrase="$1"
            shift
            ;;
    esac
done

if [[ -z "$phrase" ]]; then
    usage >&2
    exit 1
fi

if [[ -z "$model_id" ]]; then
    model_id="$(slugify "$phrase")"
fi

if [[ -z "$model_id" ]]; then
    echo "ERROR: model id is empty after slugifying phrase" >&2
    exit 1
fi

if ! [[ "$samples" =~ ^[0-9]+$ ]] || [[ "$samples" -lt 1 ]]; then
    echo "ERROR: --samples must be a positive integer" >&2
    exit 1
fi

if ! [[ "$batch_size" =~ ^[0-9]+$ ]] || [[ "$batch_size" -lt 1 ]]; then
    echo "ERROR: --batch-size must be a positive integer" >&2
    exit 1
fi

workspace="$project_root/.stacky-wake-words/$model_id"
scripts_dir="$workspace/scripts"

mkdir -p "$scripts_dir"

write_file() {
    local path="$1"
    if [[ -e "$path" && "$force" != "1" ]]; then
        echo "keep $path (use --force to overwrite)"
        return
    fi
    cat > "$path"
}

phrase_q="$(quote_sh "$phrase")"
model_id_q="$(quote_sh "$model_id")"
phoneme_q="$(quote_sh "$phoneme")"

write_file "$workspace/wake-word.env" <<EOF
# Generated by stack-chan-skill/scripts/create-wake-word-workspace.sh
WAKE_WORD_PHRASE=$phrase_q
WAKE_WORD_MODEL_ID=$model_id_q
WAKE_WORD_PHONEME=$phoneme_q
WAKE_WORD_SAMPLES=$samples
WAKE_WORD_BATCH_SIZE=$batch_size

# Piper generator model used by OHF's basic microWakeWord notebook.
PIPER_GENERATOR_MODEL=models/en_US-libritts_r-medium.pt
PIPER_GENERATOR_MODEL_URL=https://github.com/rhasspy/piper-sample-generator/releases/download/v2.0.0/en_US-libritts_r-medium.pt
PIPER_GENERATOR_CONFIG_URL=https://github.com/rhasspy/piper-sample-generator/releases/download/v2.0.0/en_US-libritts_r-medium.pt.json

# Tuning knobs passed to piper-sample-generator.
PIPER_LENGTH_SCALES="1.0 0.75 1.25 1.4"
PIPER_NOISE_SCALES="0.667 0.75 0.85 0.9 1.0 1.4"
PIPER_NOISE_SCALE_WS="0.8"
PIPER_SLERP_WEIGHTS="0.5"

# Manifest defaults. Adjust after validation.
WAKE_WORD_PROBABILITY_CUTOFF=0.97
WAKE_WORD_SLIDING_WINDOW_SIZE=5
WAKE_WORD_TENSOR_ARENA_SIZE=40000
WAKE_WORD_AUTHOR=StackChan
EOF

write_file "$workspace/training_parameters.yaml" <<EOF
window_step_ms: 10
train_dir: trained_models/$model_id
features:
  - features_dir: generated_augmented_features
    sampling_weight: 2.0
    penalty_weight: 1.0
    truth: true
    truncation_strategy: truncate_start
    type: mmap
  - features_dir: negative_datasets/local
    sampling_weight: 10.0
    penalty_weight: 1.0
    truth: false
    truncation_strategy: random
    type: mmap
training_steps:
  - 10000
positive_class_weight:
  - 1
negative_class_weight:
  - 20
learning_rates:
  - 0.001
batch_size: 128
time_mask_max_size:
  - 0
time_mask_count:
  - 0
freq_mask_max_size:
  - 0
freq_mask_count:
  - 0
eval_step_interval: 500
clip_duration_ms: 1500
target_minimization: 0.9
minimization_metric: null
maximization_metric: average_viable_recall
EOF

write_file "$scripts_dir/generate_features.py" <<'EOF'
#!/usr/bin/env python3
from pathlib import Path

from mmap_ninja.ragged import RaggedMmap
from microwakeword.audio.augmentation import Augmentation
from microwakeword.audio.clips import Clips
from microwakeword.audio.spectrograms import SpectrogramGeneration

impulse_paths = [str(path) for path in (Path("mit_rirs"),) if any(path.glob("*.wav"))]
background_paths = [
    str(path)
    for path in (Path("fma_16k"), Path("audioset_16k"))
    if any(path.glob("*.wav"))
]

clips = Clips(
    input_directory="generated_samples",
    file_pattern="*.wav",
    max_clip_duration_s=None,
    remove_silence=False,
    random_split_seed=10,
    split_count=0.1,
)

augmenter = Augmentation(
    augmentation_duration_s=3.2,
    augmentation_probabilities={
        "SevenBandParametricEQ": 0.1,
        "TanhDistortion": 0.1,
        "PitchShift": 0.1,
        "BandStopFilter": 0.1,
        "AddColorNoise": 0.1,
        "AddBackgroundNoise": 0.75,
        "Gain": 1.0,
        "RIR": 0.5,
    },
    impulse_paths=impulse_paths,
    background_paths=background_paths,
    background_min_snr_db=-5,
    background_max_snr_db=10,
    min_jitter_s=0.195,
    max_jitter_s=0.205,
)

output_root = Path("generated_augmented_features")
output_root.mkdir(exist_ok=True)

for split in ("training", "validation", "testing"):
    split_name = "train"
    repetition = 2
    slide_frames = 10
    if split == "validation":
        split_name = "validation"
        repetition = 1
    elif split == "testing":
        split_name = "test"
        repetition = 1
        slide_frames = 1

    out_dir = output_root / split
    out_dir.mkdir(exist_ok=True)
    spectrograms = SpectrogramGeneration(
        clips=clips,
        augmenter=augmenter,
        slide_frames=slide_frames,
        step_ms=10,
    )
    RaggedMmap.from_generator(
        out_dir=str(out_dir / "wakeword_mmap"),
        sample_generator=spectrograms.spectrogram_generator(split=split_name, repeat=repetition),
        batch_size=100,
        verbose=True,
    )
EOF

write_file "$scripts_dir/generate_local_negatives.py" <<'EOF'
#!/usr/bin/env python3
from pathlib import Path

from mmap_ninja.ragged import RaggedMmap
from microwakeword.audio.clips import Clips
from microwakeword.audio.spectrograms import SpectrogramGeneration

clips = Clips(
    input_directory="audioset_16k",
    file_pattern="*.wav",
    min_clip_duration_s=3.5,
    random_split_seed=11,
    split_count=0.1,
)

output_root = Path("negative_datasets/local")
output_root.mkdir(parents=True, exist_ok=True)

for split in ("training", "validation", "testing"):
    split_name = "train"
    if split == "validation":
        split_name = "validation"
    elif split == "testing":
        split_name = "test"

    out_dir = output_root / split
    out_dir.mkdir(parents=True, exist_ok=True)
    spectrograms = SpectrogramGeneration(
        clips=clips,
        step_ms=10,
        split_spectrogram_duration_s=3.2,
    )
    RaggedMmap.from_generator(
        out_dir=str(out_dir / "background_mmap"),
        sample_generator=spectrograms.spectrogram_generator(split=split_name),
        batch_size=100,
        verbose=True,
    )
EOF

write_file "$scripts_dir/download_backgrounds.py" <<'EOF'
#!/usr/bin/env python3
import tarfile
import subprocess
import zipfile
from pathlib import Path

import datasets
import librosa
import numpy as np
import scipy.io.wavfile
from tqdm import tqdm

def download(url: str, path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists():
        return
    print(f"download {url}")
    subprocess.run(["curl", "-L", "--retry", "5", "--fail", url, "-o", str(path)], check=True)

def write_wav(path: Path, sample_rate: int, audio: np.ndarray) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    scipy.io.wavfile.write(path, sample_rate, (audio * 32767).astype(np.int16))

def decoder_audio(decoder):
    samples = decoder.get_all_samples()
    audio = samples.data.squeeze().numpy()
    return samples.sample_rate, audio

rir_dir = Path("mit_rirs")
if not any(rir_dir.glob("*.wav")):
    rir_dir.mkdir(exist_ok=True)
    rir_dataset = datasets.load_dataset(
        "davidscripka/MIT_environmental_impulse_responses",
        split="train",
        streaming=True,
    )
    for index, row in enumerate(tqdm(rir_dataset, desc="MIT RIR")):
        sample_rate, audio = decoder_audio(row["audio"])
        write_wav(rir_dir / f"rir_{index:05d}.wav", sample_rate, audio)

audioset_tar = Path("audioset/bal_train09.tar")
download(
    "https://huggingface.co/datasets/agkphysics/AudioSet/resolve/196c0900867eff791b8f4d4be57db277e9a5b131/bal_train09.tar",
    audioset_tar,
)
audioset_audio_dir = Path("audioset/audio")
if not audioset_audio_dir.exists():
    with tarfile.open(audioset_tar) as tar:
        tar.extractall("audioset")

audioset_out = Path("audioset_16k")
if not any(audioset_out.glob("*.wav")):
    audioset_out.mkdir(exist_ok=True)
    audioset_files = sorted(audioset_audio_dir.glob("**/*.flac"))
    for path in tqdm(audioset_files, desc="AudioSet 16k"):
        audio, sample_rate = librosa.load(path, sr=16000, mono=True)
        write_wav(audioset_out / path.with_suffix(".wav").name, sample_rate, audio)

fma_zip = Path("fma/fma_xs.zip")
download("https://huggingface.co/datasets/mchl914/fma_xsmall/resolve/main/fma_xs.zip", fma_zip)
fma_audio_dir = Path("fma/fma_small")
if not fma_audio_dir.exists():
    with zipfile.ZipFile(fma_zip) as zf:
        zf.extractall("fma")

fma_out = Path("fma_16k")
if not any(fma_out.glob("*.wav")):
    fma_out.mkdir(exist_ok=True)
    fma_files = sorted(fma_audio_dir.glob("**/*.mp3"))
    for path in tqdm(fma_files, desc="FMA 16k"):
        audio, sample_rate = librosa.load(path, sr=16000, mono=True)
        write_wav(fma_out / path.with_suffix(".wav").name, sample_rate, audio)
EOF

write_file "$scripts_dir/write_manifest.py" <<'EOF'
#!/usr/bin/env python3
import json
import os
from pathlib import Path

phrase = os.environ["WAKE_WORD_PHRASE"]
model_id = os.environ["WAKE_WORD_MODEL_ID"]
author = os.environ.get("WAKE_WORD_AUTHOR", "StackChan")
cutoff = float(os.environ.get("WAKE_WORD_PROBABILITY_CUTOFF", "0.97"))
window = int(os.environ.get("WAKE_WORD_SLIDING_WINDOW_SIZE", "5"))
arena = int(os.environ.get("WAKE_WORD_TENSOR_ARENA_SIZE", "40000"))

model_path = Path("trained_models") / model_id / "tflite_stream_state_internal_quant" / "stream_state_internal_quant.tflite"
out_dir = Path("dist")
out_dir.mkdir(exist_ok=True)
tflite_out = out_dir / f"{model_id}.tflite"
manifest_out = out_dir / f"{model_id}.json"

if not model_path.exists():
    raise SystemExit(f"missing trained model: {model_path}")

tflite_out.write_bytes(model_path.read_bytes())
manifest = {
    "type": "micro",
    "wake_word": phrase,
    "author": author,
    "model": tflite_out.name,
    "trained_languages": ["en"],
    "version": 2,
    "micro": {
        "probability_cutoff": cutoff,
        "feature_step_size": 10,
        "sliding_window_size": window,
        "tensor_arena_size": arena,
        "minimum_esphome_version": "2024.7.0",
    },
}
manifest_out.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
print(manifest_out)
print(tflite_out)
EOF

write_file "$workspace/run.sh" <<'EOF'
#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")"
set -a
source ./wake-word.env
set +a

cmd="${1:-help}"

install_python_deps() {
    python3 -m pip install --upgrade pip
    python3 -m pip install \
        "git+https://github.com/whatsnowplaying/audio-metadata@d4ebb238e6a401bb1a5aaaac60c9e2b3cb30929f" \
        datasets scipy numpy tqdm mmap_ninja pyyaml torch torchaudio torchcodec tensorboard piper-phonemize-cross==1.2.1
    if [[ "$(uname -s)" == "Darwin" ]]; then
        python3 -m pip install 'git+https://github.com/puddly/pymicro-features@puddly/minimum-cpp-version'
    fi
    if [[ ! -d microWakeWord ]]; then
        git clone https://github.com/OHF-Voice/micro-wake-word microWakeWord
    fi
    python3 - <<'PY'
from pathlib import Path
path = Path("microWakeWord/microwakeword/audio/clips.py")
text = path.read_text(encoding="utf-8")
if "def _audio_array(audio):" not in text:
    text = text.replace(
        "from microwakeword.audio.audio_utils import remove_silence_webrtc\n\n\nclass Clips:",
        "from microwakeword.audio.audio_utils import remove_silence_webrtc\n\n\n"
        "def _audio_array(audio):\n"
        "    if hasattr(audio, \"get_all_samples\"):\n"
        "        return audio.get_all_samples().data.squeeze().numpy()\n"
        "    return audio[\"array\"]\n\n\n"
        "class Clips:",
    )
    text = text.replace('clip_audio = clip["audio"]["array"]', 'clip_audio = _audio_array(clip["audio"])')
    text = text.replace('clip_audio = rand_audio_entry["audio"]["array"]', 'clip_audio = _audio_array(rand_audio_entry["audio"])')
    path.write_text(text, encoding="utf-8")
PY
    python3 - <<'PY'
from pathlib import Path
path = Path("microWakeWord/microwakeword/audio/audio_utils.py")
text = path.read_text(encoding="utf-8")
text = text.replace(
    "frontend_result = micro_frontend.process_samples(\n"
    "                audio_samples[audio_idx : audio_idx + 160 * 2]\n"
    "            )",
    "process_samples = getattr(\n"
    "                micro_frontend, \"process_samples\", micro_frontend.ProcessSamples\n"
    "            )\n"
    "            frontend_result = process_samples(\n"
    "                audio_samples[audio_idx : audio_idx + 160 * 2]\n"
    "            )",
)
path.write_text(text, encoding="utf-8")
PY
    python3 - <<'PY'
from pathlib import Path
path = Path("microWakeWord/microwakeword/train.py")
text = path.read_text(encoding="utf-8")
if "def _metric_value(value):" not in text:
    text = text.replace(
        "\ndef validate_nonstreaming(config, data_processor, model, test_set):",
        "\n\ndef _metric_value(value):\n"
        "    return value.numpy() if hasattr(value, \"numpy\") else value\n"
        "\n\ndef validate_nonstreaming(config, data_processor, model, test_set):",
    )
text = text.replace('result["fp"].numpy()', '_metric_value(result["fp"])')
text = text.replace('ambient_predictions["tp"].numpy()', '_metric_value(ambient_predictions["tp"])')
text = text.replace('ambient_predictions["fp"].numpy()', '_metric_value(ambient_predictions["fp"])')
text = text.replace('ambient_predictions["fn"].numpy()', '_metric_value(ambient_predictions["fn"])')
path.write_text(text, encoding="utf-8")
PY
    python3 - <<'PY'
from pathlib import Path
path = Path("microWakeWord/microwakeword/test.py")
text = path.read_text(encoding="utf-8")
text = text.replace("np.trapz(", "np.trapezoid(")
path.write_text(text, encoding="utf-8")
PY
    python3 -m pip install -e ./microWakeWord
    if [[ ! -d piper-sample-generator ]]; then
        if [[ "$(uname -s)" == "Darwin" ]]; then
            git clone -b mps-support https://github.com/kahrendt/piper-sample-generator
        else
            git clone https://github.com/rhasspy/piper-sample-generator
        fi
    fi
    python3 - <<'PY'
from pathlib import Path
path = Path("piper-sample-generator/generate_samples.py")
text = path.read_text(encoding="utf-8")
text = text.replace("torch.load(model_path)", "torch.load(model_path, weights_only=False)")
path.write_text(text, encoding="utf-8")
PY
}

download_piper_model() {
    mkdir -p models
    if [[ ! -f "$PIPER_GENERATOR_MODEL" ]]; then
        curl -L "$PIPER_GENERATOR_MODEL_URL" -o "$PIPER_GENERATOR_MODEL"
    fi
    if [[ ! -f "$PIPER_GENERATOR_MODEL.json" ]]; then
        curl -L "$PIPER_GENERATOR_CONFIG_URL" -o "$PIPER_GENERATOR_MODEL.json"
    fi
    if [[ ! -s "$PIPER_GENERATOR_MODEL.json" || "$(wc -c < "$PIPER_GENERATOR_MODEL.json")" -lt 100 ]]; then
        cp "piper-sample-generator/models/$(basename "$PIPER_GENERATOR_MODEL").json" "$PIPER_GENERATOR_MODEL.json"
    fi
}

piper_text_args() {
    if [[ -n "${WAKE_WORD_PHONEME:-}" ]]; then
        printf '%s\0%s\0' "$WAKE_WORD_PHONEME" "--phoneme-input"
    else
        printf '%s\0' "$WAKE_WORD_PHRASE"
    fi
}

generate_samples() {
    local count="$1"
    local out_dir="$2"
    download_piper_model
    local parts=()
    while IFS= read -r -d '' part; do
        parts+=("$part")
    done < <(piper_text_args)
    python3 piper-sample-generator/generate_samples.py "${parts[0]}" \
        --model "$PIPER_GENERATOR_MODEL" \
        --max-samples "$count" \
        --batch-size "$WAKE_WORD_BATCH_SIZE" \
        --length-scales $PIPER_LENGTH_SCALES \
        --noise-scales $PIPER_NOISE_SCALES \
        --noise-scale-ws $PIPER_NOISE_SCALE_WS \
        --slerp-weights $PIPER_SLERP_WEIGHTS \
        --output-dir "$out_dir" \
        "${parts[@]:1}"
}

case "$cmd" in
    help)
        cat <<USAGE
Usage: ./run.sh <command>

Commands:
  setup       Install Python deps and clone microWakeWord + Piper sample generator.
  preview     Generate one Piper sample in preview_samples/.
  generate    Generate positive wake-word samples in generated_samples/.
  backgrounds Download RIR/noise/music audio used for positive sample augmentation.
  features    Convert generated samples to augmented microWakeWord features.
  negatives   Download pre-generated negative feature datasets from Hugging Face.
  local-negatives Generate compact negative features from downloaded AudioSet audio.
  train       Train and quantize the microWakeWord model.
  manifest    Copy the trained .tflite and write dist/${WAKE_WORD_MODEL_ID}.json.

Run order:
  ./run.sh setup
  ./run.sh preview
  ./run.sh generate
  ./run.sh backgrounds
  ./run.sh local-negatives
  ./run.sh features
  ./run.sh train
  ./run.sh manifest
USAGE
        ;;
    setup)
        install_python_deps
        download_piper_model
        ;;
    preview)
        generate_samples 1 preview_samples
        ;;
    generate)
        generate_samples "$WAKE_WORD_SAMPLES" generated_samples
        ;;
    negatives)
        mkdir -p negative_datasets
        for fname in dinner_party.zip dinner_party_eval.zip no_speech.zip speech.zip; do
            curl -L "https://huggingface.co/datasets/kahrendt/microwakeword/resolve/main/$fname" -o "negative_datasets/$fname"
            unzip -qo "negative_datasets/$fname" -d negative_datasets
        done
        ;;
    backgrounds)
        python3 scripts/download_backgrounds.py
        ;;
    features)
        python3 scripts/generate_features.py
        ;;
    local-negatives)
        python3 scripts/generate_local_negatives.py
        ;;
    train)
        python3 -m microwakeword.model_train_eval \
            --training_config=training_parameters.yaml \
            --train 1 \
            --restore_checkpoint 1 \
            --test_tf_nonstreaming 0 \
            --test_tflite_nonstreaming 0 \
            --test_tflite_nonstreaming_quantized 0 \
            --test_tflite_streaming 0 \
            --test_tflite_streaming_quantized 1 \
            --use_weights best_weights \
            mixednet \
            --pointwise_filters "64,64,64,64" \
            --repeat_in_block "1, 1, 1, 1" \
            --mixconv_kernel_sizes "[5], [7,11], [9,15], [23]" \
            --residual_connection "0,0,0,0" \
            --first_conv_filters 32 \
            --first_conv_kernel_size 5 \
            --stride 3
        ;;
    manifest)
        python3 scripts/write_manifest.py
        ;;
    *)
        echo "unknown command: $cmd" >&2
        exit 1
        ;;
esac
EOF

write_file "$workspace/README.md" <<EOF
# Wake Word: $phrase

This workspace was generated for StackChan microWakeWord training.

## Run Order

\`\`\`bash
cd "$workspace"
./run.sh setup
./run.sh preview
./run.sh generate
./run.sh backgrounds
./run.sh local-negatives
./run.sh features
./run.sh train
./run.sh manifest
\`\`\`

The final files are:

- \`dist/$model_id.tflite\`
- \`dist/$model_id.json\`

Copy those into the firmware wake-word model packaging path only after the
remote-agent firmware has a microWakeWord TFLite Micro runner wired in.

## Phrase

- Display phrase: \`$phrase\`
- Model id: \`$model_id\`
- Piper phoneme input: \`${phoneme:-not set}\`

If the generated preview sounds wrong, recreate this workspace with
\`--phoneme\` and tune the Piper controls in \`wake-word.env\`.
EOF

chmod +x "$workspace/run.sh" "$scripts_dir/generate_features.py" "$scripts_dir/generate_local_negatives.py" "$scripts_dir/download_backgrounds.py" "$scripts_dir/write_manifest.py"

echo "Created wake-word workspace: $workspace"
echo "Next:"
echo "  cd \"$workspace\""
echo "  ./run.sh setup"
echo "  ./run.sh preview"
